export NERFBASELINES_PREFIX=/project/3dllms/melgin/conda/envs/
export NERFBASELINES_HOME_DIR_PATH=/project/3dllms/melgin/nerfbaselines-grocery/
export GROCERY_DATA_CONVERTED_UNGROUPED_DIR_PATH=/project/3dllms/DATASETS/CONVERTED/UNGROUPED/
export GROCERY_DATA_CONVERTED_GROUPED_DIR_PATH=/project/3dllms/DATASETS/CONVERTED/GROUPED/
export GROCERY_DATA_NORMAL_UNGROUPED_DIR_PATH=/project/3dllms/DATASETS/PROCESSED/
export GROCERY_DATA_NORMAL_GROUPED_DIR_PATH=/project/3dllms/DATASETS/GROUPED/
export GROCERY_RESULTS_DIR_PATH=${NERFBASELINES_HOME_DIR_PATH}results/
export GROCERY_LOGS_DIR_PATH=${NERFBASELINES_HOME_DIR_PATH}logs/
export GROCERY_CSVS_DIR_PATH=${NERFBASELINES_HOME_DIR_PATH}csv/csv_results/

export PYTHONPATH=${NERFBASELINES_HOME_DIR_PATH}:${PYTHONPATH}
